### ISSUE TITLE
Generate the data for training error

### ISSUE THREAD

**Issue by yangdaowu** [jixinya/EVP#18]
I am running python landmark / code / preProcess.py.
Then, this path does not exist. How should it be operated

Traceback (most recent call last):
  File "/home/user/PycharmProjects/EVP/EVP/train/landmark/code/preprocess.py", line 145, in <module>
    a = np.load(path)
  File "/home/user/anaconda3/envs/evp/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/PycharmProjects/EVP/EVP/train/landmark/dataset_M030/landmark/M030_fear_3_026/5.npy'

**Comment by Bacchuc** [comment]
I met the same problem. Did you find a solution later?

**Comment by Bacchuc** [comment]
> I am running python landmark / code / preProcess.py. Then, this path does not exist. How should it be operated
> 
> Traceback (most recent call last): File "/home/user/PycharmProjects/EVP/EVP/train/landmark/code/preprocess.py", line 145, in a = np.load(path) File "/home/user/anaconda3/envs/evp/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: '/home/user/PycharmProjects/EVP/EVP/train/landmark/dataset_M030/landmark/M030_fear_3_026/5.npy'

I met the same problem. Did you find a solution later?
